import os
import sys
import shutil
import subprocess
from pathlib import Path

# ============================================================
# Configuration
# ============================================================

ROOT = Path(__file__).parent.resolve()
STATIC_DIR = ROOT / "static"

SRC_PY = STATIC_DIR / "mod_installer.py"
OUT_EXE = STATIC_DIR / "mod_installer.exe"

BUILD_DIR = ROOT / "build"
DIST_DIR = ROOT / "dist"
SPEC_FILE = ROOT / "mod_installer.spec"

# ============================================================
# Utils
# ============================================================

def rm(path: Path):
    if path.exists():
        if path.is_dir():
            shutil.rmtree(path, ignore_errors=True)
        else:
            path.unlink(missing_ok=True)

def run(cmd: str):
    print(f"▶ {cmd}")
    result = subprocess.run(cmd, shell=True)
    if result.returncode != 0:
        print("❌ Build failed.")
        sys.exit(result.returncode)

# ============================================================
# Spec File Generator (fixed)
# ============================================================

def write_spec():
    """
    Write a PyInstaller spec file with POSIX paths so Windows doesn't escape.
    """
    src = SRC_PY.as_posix()
    root = ROOT.as_posix()

    SPEC_FILE.write_text(f"""
# Auto-generated by build_mod_installer.py
block_cipher = None

a = Analysis(
    ['{src}'],
    pathex=['{root}'],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='mod_installer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    console=False,
    windowed=True,
    icon=None
)
""".strip(), encoding="utf-8")

    print(f"📄 Wrote safe spec file: {SPEC_FILE}")

# ============================================================
# Main Build Process
# ============================================================

def main():
    print("==============================================")
    print("     DEADLOCK MOD INSTALLER - BUILD TOOL")
    print("==============================================")

    if not SRC_PY.exists():
        print(f"❌ Missing source installer: {SRC_PY}")
        sys.exit(1)

    print("🧹 Cleaning old build artifacts...")
    rm(BUILD_DIR)
    rm(DIST_DIR)
    rm(SPEC_FILE)
    rm(ROOT / "__pycache__")

    write_spec()

    cmd = f'"{sys.executable}" -m PyInstaller "{SPEC_FILE}" --noconfirm'
    run(cmd)

    built_exe = DIST_DIR / "mod_installer.exe"
    if not built_exe.exists():
        print("❌ EXE did not build.")
        sys.exit(1)

    rm(OUT_EXE)
    shutil.move(str(built_exe), str(OUT_EXE))

    print(f"✅ Build complete: {OUT_EXE}")

    print("🧽 Final cleanup...")
    rm(BUILD_DIR)
    rm(DIST_DIR)
    rm(SPEC_FILE)

    print("✨ All clean! Installer ready.")


if __name__ == "__main__":
    main()
